build1:
  tags: 
    - eda
    - docker
  stage: build
  script:
#     - pwd
#     - ls
#     - ls /
#     - ls /projects 
    - source /projects/oss-cad-suite/release/environment
    - unset VERILATOR_ROOT
    - which iverilog
    - make test
    - make test_axi
    - make test_verilator
    - make test_synth
