# before_script:
#   - echo "Before script section"
#   - echo "For example you might run an update here or install a build dependency"
#   - echo "Or perhaps you might print out some debugging details"
# 
# after_script:
#   - echo "After script section"
#   - echo "For example you might do some cleanup here"

build1:
  tags: 
    - eda
    - docker
  stage: build
  script:
#     - cat generated-bash-script | /bin/bash
    - echo "Do your build here"
    - pwd
    - ls
    - ls /
#     - ls /etc/gitlab-runner
    - ls /projects
    - chmod +x /projects/oss-cad-suite/environment
    - source /projects/oss-cad-suite/environment | /bin/bash
    - which iverilog
    - make test
    - make test_axi
    - make test_verilator
    - make test_synth

# test1:
#   stage: test
#   script:
#     - echo "Do a test here"
#     - echo "For example run a test suite"
# 
# test2:
#   stage: test
#   script:
#     - echo "Do another parallel test here"
#     - echo "For example run a lint test"
# 
# deploy1:
#   stage: deploy
#   script:
#     - echo "Do your deploy here"
#   environment: production
