pipelines:
  default:
      - step:
          name: Test OSS-CAD-SUITE
          runs-on: 
            - 'linux.shell'
          script:
            - echo "Checks that the execuatbales from oss-cad-suite are available and execuatable";
            - source /projects/oss-cad-suite/release/environment
            - unset VERILATOR_ROOT
            - which iverilog
            - make test
            - make test_axi
            - make test_verilator
