# build1:
#   tags: 
#     - eda
#     - docker
#   stage: build
#   script:
# #     - pwd
# #     - ls
# #     - ls /
# #     - ls /projects 
#     - source /projects/oss-cad-suite/release/environment
#     - unset VERILATOR_ROOT
#     - which iverilog
#     - make test
#     - make test_axi
#     - make test_verilator
#     - make test_synth# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  custom:
    customPipelineWithRunnerAndCache:
      - step:
          name: Step 1
          runs-on: 
            - 'linux.shell'
          script:
            - echo "This step will run on a linux shell runner.";
            - pwd
            - ls
            - ls /
            - ls /projects 
            - source /projects/oss-cad-suite/release/environment
            - unset VERILATOR_ROOT
            - which iverilog
            - make test
            - make test_axi
            - make test_verilator
